### ISSUE TITLE
Should SHiELD be using a Gregorian calendar?

### ISSUE THREAD

**Issue by spencerkclark** [NOAA-GFDL/FMScoupler#103]
### Disclaimer

This is a bit in the weeds and is not a blocking issue, but I have often wondered whether SHiELD should be using a Gregorian calendar instead of a Julian calendar.  I just wanted to put down some thoughts as some investigation provided me a little more clarity on this question than I had previously.  I am increasingly thinking the answer should be "yes," but I would be curious to know what the rationale was behind using a Julian calendar initially.

### Issue

In thinking about doing extended simulations using SHiELD, NOAA-GFDL/atmos_drivers#36, it occurred to me to look into how time deltas were computed in its physics, e.g. in [this line](https://github.com/NOAA-GFDL/SHiELD_physics/blob/5e5e100c068d55b8247dcb428f9df36fb31bdf35/GFS_layer/GFS_driver.F90#L316) or [when computing the Julian day](https://github.com/NOAA-GFDL/SHiELD_physics/blob/5e5e100c068d55b8247dcb428f9df36fb31bdf35/gsmphys/radiation_astronomy.f#L556) in the astronomy module, as I wanted to make sure that they were safe from the same integer overflow problem described in NOAA-GFDL/atmos_drivers#35.  I believe that they are, because 32-bit integer values are only used for computing the Julian day (and differences between Julian days), and time deltas in units of seconds are computed using 64-bit floats.  

But in investigating these functions / subroutines I also wanted to see what kind of calendar they assumed the dates provided used.  This is relevant for longer simulations, since the Julian (what the SHiELD coupler currently uses) and Gregorian calendars, for example, handle whether year 2100 is a leap year differently.  In the Julian calendar it is a leap year, but in the Gregorian calendar it is not.  

To compute these time deltas, SHiELD uses functions / subroutines defined in the [NCEPLIBS-w3emc library](https://github.com/NOAA-EMC/NCEPLIBS-w3emc/tree/develop), like [`iw3jdn`](https://github.com/NOAA-EMC/NCEPLIBS-w3emc/blob/develop/src/iw3jdn.f), which computes the Julian day.  This function is also called in downstream subroutines like [`w3difdat`](https://github.com/NOAA-EMC/NCEPLIBS-w3emc/blob/develop/src/w3difdat.f).  While the comment in `iw3jdn` does not explicitly say which calendar it expects the input date to use, it refers to an old ACM letter to the editor:

> Henry F. Fliegel and Thomas C. van Flandern. 1968. Letters to the editor: a machine algorithm for processing calendar dates. Commun. ACM 11, 10 (Oct. 1968), 657. https://doi.org/10.1145/364096.364097

This letter makes it clear that this algorithm assumes the date comes from a Gregorian calendar.  We can also assess this empirically by comparing the result of `w3difdat` when called to determine the time difference between two dates straddling the potential leap year in 2100:

```
program test
  integer :: jdat(8), idat(8)
  real(kind=8) :: rinc(5)

  jdat = (/ 2100, 3, 1, 0, 0, 0, 0, 0 /)
  idat = (/ 2100, 2, 1, 0, 0, 0, 0, 0 /)
  call w3difdat(jdat, idat, 1, rinc)
  print *, jdat
  print *, idat
  print *, rinc
end program test
```

If we run this program, we obtain the following output:

```
        2100           3           1           0           0           0           0           0
        2100           2           1           0           0           0           0           0
   28.000000000000000        0.0000000000000000        0.0000000000000000        0.0000000000000000        0.0000000000000000
```

indicating that the difference between March 1st, 2100 and February 1st, 2100 is 28 days.  This suggests 2100 does not have a leap year, and therefore that the algorithm expects the dates come from a Gregorian calendar (perhaps not surprisingly, since this should help the physics produce the most accurate weather forecasts).

For typical date ranges of SHiELD simulations, this is not important—the Julian and Gregorian calendars are effectively the same between 1901 and 2099—but in extended simulations, this mismatch in calendars starts to become relevant, and there will be an inconsistency between time deltas computed using the FMS time manager and time deltas computed using the physics.  

### Why might we care about this in the present day?

While the Julian calendar is still used in some settings, the Gregorian calendar is the standard calendar we use in everyday life, and therefore makes the most sense to use for a weather model.  While a calendar change should not affect answers in the present day, it would show up in the metadata of data output by SHiELD, which could make it easier to interact with in downstream libraries (e.g. in Python it would allow dates to be safely represented using standard library `datetime.datetime` objects or `numpy.datetime64` values).

Anyway some food for thought, but again I want to emphasize that this is not a blocking issue.

cc: @lharris4

**Comment by spencerkclark** [comment]
Another point in favor of the Gregorian calendar is that it is also what [the UFS uses in its driver](https://github.com/ufs-community/ufs-weather-model/blob/458486087147216a9154f2169f8a338ff747943c/driver/UFS.F90#L94-L98).

**Comment by lharris4** [comment]
Thank you @spencerkclark for bringing this to our attention.  I am not clear why SHiELD uses the Julian and not Gregorian calendar. This might have been something done in the early days of fvGFS when there were very many tasks that needed to be done in a short time. I would presume implementing the Gregorian calendar should be straightforward but may break existing restarts.

**Comment by spencerkclark** [comment]
Thanks @lharris4—that makes sense.  That's a good point about restarts.  I suspect we could implement things in a backwards compatible way.  In other words we could maintain the ability to run with a Julian calendar, but encourage switching over to using the Gregorian calendar.

**Comment by bensonr** [comment]
@spencerkclark - have you put in a PR with the update to support the Gregorian calendar?  IIRC, it's a two-line fix that was applied to the simple coupler a few years ago and can easily be added to the SHiELD coupler.  Once the team running SHiELD is satisfied with using the full coupler with the appropriate do_<component>=.false., we can retire the SHiELD version.

**Comment by spencerkclark** [comment]
@bensonr I have not made a PR yet, but I'd be happy to do that.  Indeed it will be great once we move over to the full coupler, which already supports all FMS calendars.
