### ISSUE TITLE
Bug in SHiELD/coupler_main

### ISSUE THREAD

**Issue by laurenchilutti** [NOAA-GFDL/FMScoupler#139]
This line was recently changed from being 1 line to 2 and a continuation character (&) is needed at the end of line 327

https://github.com/NOAA-GFDL/FMScoupler/blob/c6fdc8710d0d7083e30eb0090035b6f8da09f0ac/SHiELD/coupler_main.F90#L327-L328

**Comment by rem1776** [comment]
fixed by #140
