### ISSUE TITLE
div_by_zero in atmos_ocean_fluxes_calc

### ISSUE THREAD

**Issue by GFDL-Eric** [NOAA-GFDL/FMScoupler#21]
I'm attempting a run through with Lori's xml, hitting a div_by_zero in this section of code which is calculating gas fluxes. https://github.com/NOAA-GFDL/FMScoupler/blob/f48e67ba9c343152045182e80df5c14021130d47/full/atmos_ocean_fluxes_calc.f90#L153 It would appear that the incoming ice gas fields are zero (this is the calling routine in atm_land_ice_flux_exchange): https://github.com/NOAA-GFDL/FMScoupler/blob/f48e67ba9c343152045182e80df5c14021130d47/full/atm_land_ice_flux_exchange.F90#L1235 I realize these values may be overridden at some point later on in the code (and hence the error probably doesn't even show up in a prod run), but should there be something here that at least warns of the div by zero, or perhaps provides a default flux value in the event of 0 fields?

**Comment by wrongkindofdoctor** [comment]
A warning might be sufficient, but I would prefer a fatal in case there are uninitialized values propagating through the code. You should consult with @cmdupuis3, since he is the land liaison.

**Comment by GFDL-Eric** [comment]
FWIW, I _think_ I've figured out the issue. It seems like the atmos_ocean_fluxes_calc call (line 1235) is expecting ex_gas_fields_ice to be populated. ex_gas_fields_ice, in turn, is supposed to be populated by the put_to_xgrid call https://github.com/NOAA-GFDL/FMScoupler/blob/f48e67ba9c343152045182e80df5c14021130d47/full/atm_land_ice_flux_exchange.F90#L1055 ...and this in turn relies upon `Ice%ocean_fields%bc(n)%field(m)%values` being populated, which is supposed to happen with this data_override call https://github.com/NOAA-GFDL/FMScoupler/blob/f48e67ba9c343152045182e80df5c14021130d47/full/atm_land_ice_flux_exchange.F90#L969 ...however, this is predicated on all of the relevant "bc" fields being included in `Ice%ocean_fields`, which in turn relies upon them being defined in the **data table**... which in this xml (and likely many others?) they assuredly aren't! As to why zeros and not missing values... I'm trying to pinpoint where this is all initialized but I'm getting a bit lost (having the gas_fields variable name oscillate between gas_fields_ice and gas_fields_ocn isn't terribly helpful).

**Comment by wrongkindofdoctor** [comment]
I _think_ I can answer the "why zeros" question. In the ice_type.F90 modules, gas_fields_ocn is [copied to Ice%ocean_fields](https://github.com/NOAA-GFDL/SIS2/blob/547c0cddeebd56c3518cc3b0e8baf44ebfa9af0b/src/ice_type.F90#L308) data via the interface [couper_type_spawn](https://github.com/NOAA-GFDL/FMS/blob/a8cb34668e4aaa77620eedad5b8dc81ab23238c5/coupler/coupler_types.F90#L733) (I've linked to the 2d-2d routine here). If you scroll down a bit, you'll see that the var%bc%field%values are set to 0.0 after the arrays are allocated:
          [var%bc(n)%field(m)%values(:,:) = 0.0](https://github.com/NOAA-GFDL/FMS/blob/a8cb34668e4aaa77620eedad5b8dc81ab23238c5/coupler/coupler_types.F90#L812)

**Comment by GFDL-Eric** [comment]
I think we've answered the question of why the zeros have propagated through, but we haven't really answered the question of why they are set to zero to begin with... my inclination is that it was never really noticed (since it goes away in prod), but I'll have to consult Lori to see if she has thoughts on how to proceed. Since I don't know how long the resolution will take, I'd push to 2020.02.
