### ISSUE TITLE
FMScoupler calls to ice_model_restart require time argument for new IO

### ISSUE THREAD

**Issue by wrongkindofdoctor** [NOAA-GFDL/FMScoupler#30]
An optional restart_time argument needs to be passed to ice_model_restart to support the implementation of the new FMS IO in ice_SIS and, eventually, SIS2. This change allows the user to override the default time value of 1.0 days that is set in ice_model_restart, as when writing intermediate restart files.

**Comment by bensonr** [comment]
@wrongkindofdoctor can you explain why this change is necessary?  Changing an interface at this level is a big deal and would like some background why the Ice type is no longer needed.
