### ISSUE TITLE
Support for Gregorian calendar

### ISSUE THREAD

**Issue by andrew-c-ross** [NOAA-GFDL/FMScoupler#34]
FMScoupler does not currently support the Gregorian calendar.

Gregorian does appear to be supported by FMS, so are there any historical reasons for this lack of support or other issues with the Gregorian calendar?

I running some MOM6 simulations with realistic tidal forcing, and using the Gregorian calendar is particularly useful for this case.

As far as I can tell supporting the Gregorian calendar would only require importing it from time_manager_mod in coupler_main and then adding a case statement for it. With these changes my MOM6 simulations run fine. I'd be happy to send a PR.

**Comment by colingladueNOAA** [comment]
We would be more than happy to accept this PR. I look forward to reviewing it.
