### ISSUE TITLE
How to start learning FMScoupler?

### ISSUE THREAD

**Issue by manmeet3591** [NOAA-GFDL/FMScoupler#45]
I have to learn to couple different ESM component models. Where do I start to learn this FMScoupler. Are there any sample examples?

**Comment by thomas-robinson** [comment]
@manmeet3591 I'm not quite sure what you re looking for.  Could you provide more details?  Are you looking for a model that runs with FMScoupler?  Documentation?

**Comment by manmeet3591** [comment]
@thomas-robinson I am looking to couple the NOAH-MP land model with the IITM-ESM model. IITM-ESM has an atmospheric model based on GFS and ocean is MOM4p1. FMS is used for coupling as of now in the model. I guess FMScoupler can be used for coupling components such as NOAH-MP land model to the ocean and atmosphere that I have. And since the I/O and other things are already FMS based in the model at my research institute, FMScoupler should work ideally. But I am finding difficult to understand how to exactly couple using FMScoupler. So, if you can please help with any documentation or tutorial demonstrating coupling of dummy atmosphere/ocean using FMScoupler, it would be great.

**Comment by thomas-robinson** [comment]
@manmeet3591 there are null models available on the NOAA-GFDL github.  https://github.com/NOAA-GFDL/atmos_null https://github.com/NOAA-GFDL/ocean_null https://github.com/NOAA-GFDL/land_null https://github.com/NOAA-GFDL/ice_null .  They are a good place to start I guess.  The land model works with the simple coupler, not the full coupler.  

Is this what you are looking for?

**Comment by bensonr** [comment]
@manmeet3591 - I have worked with the latest U.S. NWS GFS implementation as well as previous versions.  Do you also use the GFS physics within ITM-ESM?  If so, is the land model (NOAH or another variant) still embedded and called from within the atmospheric physics driver?

**Comment by manmeet3591** [comment]
> @manmeet3591 - I have worked with the latest U.S. NWS GFS implementation as well as previous versions. Do you also use the GFS physics within ITM-ESM? If so, is the land model (NOAH or another variant) still embedded and called from within the atmospheric physics driver?

@bensonr Yes I have the GFS physics within IITM-ESM and there is NOAH land model embedded inside which is called from the atmospheric physics driver. I have to couple NOAH-MP crop within the physics.

**Comment by manmeet3591** [comment]
> @manmeet3591 there are null models available on the NOAA-GFDL github. https://github.com/NOAA-GFDL/atmos_null https://github.com/NOAA-GFDL/ocean_null https://github.com/NOAA-GFDL/land_null https://github.com/NOAA-GFDL/ice_null . They are a good place to start I guess. The land model works with the simple coupler, not the full coupler.
> 
> Is this what you are looking for?

@thomas-robinson Thank you so much for sharing the links. I will go through them. I am sorry but I didn't get the difference between a simple coupler and a full coupler. Is it that a full coupler does concurrent coupling whereas simple is sequential?

**Comment by bensonr** [comment]
@manmeet3591 The simple coupler is for running an atmospheric-land-ice system only and any needed BCs would come in via the ice component.

With the NOAH model already embedded in the physics, the most sensible option is to either replace NOAH with NOAH-MP or add the NOAH-MP crop capability within the physics driver at the appropriate place.  Any missing fields can be imported via the physics driver interface.

**Comment by manmeet3591** [comment]
@bensonr Thank you very much. I will try these out. I hope I can trouble you with more questions as they come.

**Comment by bensonr** [comment]
@manmeet3591 I will do my best to answer them based on my limited knowledge of your exact GFS implementation.

**Comment by manmeet3591** [comment]
@bensonr Thank you very much.
