### ISSUE TITLE
Add simple coupler

### ISSUE THREAD

**Issue by underwoo** [NOAA-GFDL/FMScoupler#5]
Add GFDL simple coupler to the repository.

**Comment by underwoo** [comment]
A proposal for the merge is in the fork [https://github.com/underwoo/coupler](underwoo/coupler) on branch [https://github.com/NOAA-GFDL/coupler/compare/master...underwoo:5-add.simple.coupler](5-add.simple.coupler).

**Comment by thomas-robinson** [comment]
@underwoo The code in your fork is based on warsaw_201803.  I have an updated xanadu version (#6 ) with simple coupler updates for xanadu patch on [thomas-robinson/coupler](https://github.com/thomas-robinson/coupler) branch [1-add-simple-coupler](https://github.com/thomas-robinson/coupler/tree/1-add-simple-coupler).  I still have to test this.

**Comment by underwoo** [comment]
@thomas-robinson, thank you for catching this. I have updated the master branch (from our github repository) and updated the fork [underwoo/coupler](https://github.com/underwoo/coupler) on branch [5-add.simple.coupler](https://github.com/NOAA-GFDL/coupler/compare/master...underwoo:5-add.simple.coupler) with the xanadu release.  Please give this new version a try.

**Comment by thomas-robinson** [comment]
@underwoo I had to make some changes to my  [1-add-simple-coupler](https://github.com/thomas-robinson/coupler/tree/1-add-simple-coupler) branch to be compatible with the land_null repo.  The model we've been running uses land_amip which is a little bit different.

**Comment by underwoo** [comment]
Merge complete.  Please let me know of any issues.

**Comment by thomas-robinson** [comment]
@underwoo Can you put in a pull request, or should I put one in with my fork?

**Comment by underwoo** [comment]
I think yours is the most up-to-date, at least you likely did some
testing.  Please create the pull request from your fork.
--
Seth Underwood

S/W Development Process Lead
Modeling Systems Group
GFDL/NOAA/DOC
201 Forrestal Road
Princeton, NJ 08540-6649

(609) 452-5847 Office
(304) 376-9002 Cell
(609) 987-5063 Fax
Seth.Underwood@noaa.gov
