### ISSUE TITLE
coupler_main.F90 needs to verify the return code from get_cpu_affinity

### ISSUE THREAD

**Issue by underwoo** [NOAA-GFDL/FMScoupler#7]
The call to [get_cpu_affinity](https://github.com/NOAA-GFDL/FMS/blob/master/mpp/affinity.c#L39) in `coupler_main.F90` needs to ensure a valid return cpu number (/= -1) is returned.

**Comment by bensonr** [comment]
Need to have a discussion of the expected behavior when an error return code is generated.  Two possible scenarios:
  1) abort with a detailed message
  2) continue with warning messages and affinity unenforced

**Comment by thomas-robinson** [comment]
@bensonr I would prefer an error with a message.  This is a potential performance issue.  If the model is able to run but does not get the correct affinity, it could potentially cause slow downs of an order of magnitude.  That is unacceptable, so the model should crash with a detailed error message.

**Comment by jwdGFDL** [comment]
I agree with Tom; the run should abort with a clear message. First, there are way too many warning messages that end up dumped in the output. If the job times out, where does the unwary user begin to look? Further, realistic use of threads requires proper core affinity. If there's sufficient user pressure, we could provide an input option to ignore the lack of affinity. But right now I can't think of a valid reason why lack of thread-to-core affinity is  OK.

**Comment by underwoo** [comment]
I also agree with @thomas-robinson and @jwdGFDL.  A quick termination with a clear message is desirable.

**Comment by wrongkindofdoctor** [comment]
+1 For crash+unambiguous message

**Comment by bensonr** [comment]
Thoughts on this error message:

get_cpu_affinity has returned an invalid value. Check your mpi-task spacing, ncores_per_node, and thread values. File a helpdesk ticket if issues persist.

**Comment by underwoo** [comment]
That looks better than many of the error messages already in the code.  I approve. :+1:

**Comment by bensonr** [comment]
There is now a fix in the branch 7_affinity_error_handling in my fork with error handling for get_cpu_affinity and also set_cpu_affinity.  I have also asked @underwoo for an additional fix to FMS::mpp/affinity.c to allow for correct error handling of set_cpu_affinity.

**Comment by bensonr** [comment]
The affinity handling is being rewritten within NOAA-GFDL/FMS to handle slurm's utilization of cpusets.  As part of the udpate, a routine will be created to handle affinity placement.  The code now existing in coupler_main.F90 for affinity placement will be replaced by a call to a subroutine in FMS to handle all affinity placement (see [FMS issue #112](https://github.com/NOAA-GFDL/FMS/issues/112))

**Comment by thomas-robinson** [comment]
@bensonr Is this issue reolved with #17 ?  If so, we can close it

**Comment by thomas-robinson** [comment]
Closing this issue after consulting with @bensonr
