### ISSUE TITLE
Passing additional surface variables into the atmospheric model

### ISSUE THREAD

**Issue by zhihong-tan** [NOAA-GFDL/FMScoupler#92]
A new boundary layer scheme (NCEP TKE-based eddy-diffusivity mass-flux scheme) is being implemented in the prototype-AM5 model, and it requires five additional surface variables (shflx, lhflx, wind, thv_atm, and thv_surf) as inputs. Thus, I would like to add a few lines in the surface coupler (full/atm_land_ice_flux_exchange.F90 and shared/surface_flux.F90) to pass these variables into the atmospheric model.

This issue is associated with the issue I just opened for the atmos_drivers repository.

**Comment by rem1776** [comment]
added with #93
